spring:
  datasource:
    url: jdbc:oracle:thin:@system_high?TNS_ADMIN=/Users/ddang_me/Oracle/Wallet_system
    username: ride_camp
    password: Qwerty123456
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    org.hibernate.SQL: debug
